Blockly.Msg.WEBSERIAL_SELECT_COMPORT = "Web Serial Status";
Blockly.Msg.WEBSERIAL_BUTTON_CONNECT_SHOW = "Open";
Blockly.Msg.WEBSERIAL_BUTTON_CLOSE_SHOW = "Close";
Blockly.Msg.WEBSERIAL_OPEN = "Web Serial Port Open";
Blockly.Msg.WEBSERIAL_CLOSE = "Web Serial Port Close";
Blockly.Msg.ROBOFLY_SHOW = "ROBOFLY";
Blockly.Msg.WEBSERIAL_UNLOCK_SHOW = "drone unlock";
Blockly.Msg.WEBSERIAL_LOCK_SHOW = "drone lock";
Blockly.Msg.WEBSERIAL_SHOW_SHOW = "show";
