Blockly.Msg.WEBSERIAL_SELECT_COMPORT = "Web Serial 序列埠状态";
Blockly.Msg.WEBSERIAL_BUTTON_CONNECT_SHOW = "开启";
Blockly.Msg.WEBSERIAL_BUTTON_CLOSE_SHOW = "关闭";
Blockly.Msg.WEBSERIAL_OPEN = "Web Serial 开启序列埠";
Blockly.Msg.WEBSERIAL_CLOSE = "Web Serial 关闭序列埠";
Blockly.Msg.ROBOFLY_SHOW = "ROBOFLY";
Blockly.Msg.WEBSERIAL_UNLOCK_SHOW = "无人机解锁";
Blockly.Msg.WEBSERIAL_LOCK_SHOW = "无人机上锁";
Blockly.Msg.WEBSERIAL_SHOW_SHOW = "显示";
